version: '3.8'  # Make sure the version is compatible

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - neo4j  # You can leave this as is since it won't cause issues

  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: "neo4j/password"
    # Remove healthcheck configuration
