version: '3.8'
services:
  test-neo4j:
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=neo4j/test_password
    ports:
      - "7475:7474"
      - "7688:7687"

  test-backend:
    build:
      context: ./backend
    ports:
      - "8001:8000"  # Exposing the backend on a different port to avoid conflicts
    depends_on:
      - test-neo4j
    environment:
      NEO4J_URI: "bolt://test-neo4j:7687"
      NEO4J_USER: "neo4j"
      NEO4J_PASSWORD: "test_password"
